/**
 * @file src/chat/codex-usage-captures.fixtures.ts
 * @exports WEEKLY_ONLY_IDLE, WEEKLY_ONLY_97, WEEKLY_ONLY_SPENT, BOTH_WINDOWS, LEGACY_RELATIVE_RESETS, UNRECOGNISED_WINDOW, NO_WINDOW_MIDSESSION
 * @depends ./codex-usage-decode
 * @purpose The codex `rate_limits` payloads this decoder is tested against - every one SLICED
 *   BYTE-FOR-BYTE out of a real ~/.codex/sessions rollout line, never composed by hand. Each RAW
 *   constant is the exact source substring (key order, `0.0` spelling and all); the exported fixture is
 *   JSON.parse of it, so no test can assert against a shape the vendor has not actually sent.
 *   GENERATED by scripts/extract-codex-captures.mjs - re-run it if a new vendor shape appears in the
 *   wild; do NOT hand-edit a payload, which would quietly turn a capture back into an imagination.
 *   THE LAW THIS SERVES: tests assert the OBSERVED, not the desired.
 */
import type { CodexRateLimits } from "./codex-usage-decode.js";

/**
 * TODAY'S REAL STATE (the operator's false warning). Weekly-only window at 0% used, plus
 *   the unfunded credits wallet the old decoder read as 'subscription spent'. plan_type prolite.
 * CAPTURED VERBATIM FROM: ~/.codex/sessions/2026/07/16/rollout-2026-07-16T15-34-06-019f6aeb-6cdb-7b51-b64d-d3b78e51f4e4.jsonl
 *   line 257
 */
const WEEKLY_ONLY_IDLE_RAW =
  '{"limit_id":"codex","limit_name":null,"primary":{"used_percent":0.0,"window_minutes":10080,"resets_at":1785750348},"secondary":null,"credits":{"has_credits":false,"unlimited":false,"balance":"0"},"individual_limit":null,"plan_type":"prolite","rate_limit_reached_type":null}';

/**
 * Weekly-only at 97% used - the genuine 'running low' warning. Carries a
 *   `spend_control_reached` key the 07-16 capture does NOT: observed vendor drift, ignored safely.
 * CAPTURED VERBATIM FROM: ~/.codex/sessions/2026/07/25/rollout-2026-07-25T21-45-39-019f9a98-e4c2-7e10-bac5-7323625a3747.jsonl
 *   line 215
 */
const WEEKLY_ONLY_97_RAW =
  '{"limit_id":"codex","limit_name":null,"primary":{"used_percent":97.0,"window_minutes":10080,"resets_at":1785260749},"secondary":null,"credits":{"has_credits":false,"unlimited":false,"balance":"0"},"individual_limit":null,"spend_control_reached":null,"plan_type":"prolite","rate_limit_reached_type":null}';

/**
 * Weekly-only at 100% used - REAL exhaustion, carrying the SAME unfunded credits block as
 *   WEEKLY_ONLY_IDLE. The pair proves exhaustion tracks the window, never the wallet.
 * CAPTURED VERBATIM FROM: ~/.codex/sessions/2026/07/21/rollout-2026-07-21T21-39-57-019f85fa-30ab-7100-be75-217263c8bc75.jsonl
 *   line 116
 */
const WEEKLY_ONLY_SPENT_RAW =
  '{"limit_id":"codex","limit_name":null,"primary":{"used_percent":100.0,"window_minutes":10080,"resets_at":1785073363},"secondary":null,"credits":{"has_credits":false,"unlimited":false,"balance":"0"},"individual_limit":null,"plan_type":"plus","rate_limit_reached_type":null}';

/**
 * Both windows present (plan_type plus): a 300-minute 5h window at 27% as `primary` and a
 *   10080-minute weekly at 100% as `secondary`. The weekly moves between primary and secondary BY
 *   PLAN - which is exactly why position mapping lied.
 * CAPTURED VERBATIM FROM: ~/.codex/sessions/2026/07/09/rollout-2026-07-09T21-47-26-019f4834-c761-7111-bdfc-3f6db59c00e0.jsonl
 *   line 300
 */
const BOTH_WINDOWS_RAW =
  '{"limit_id":"codex","limit_name":null,"primary":{"used_percent":27.0,"window_minutes":300,"resets_at":1783639273},"secondary":{"used_percent":100.0,"window_minutes":10080,"resets_at":1783768191},"credits":{"has_credits":false,"unlimited":false,"balance":"0"},"individual_limit":null,"plan_type":"plus","rate_limit_reached_type":null}';

/**
 * The 2025 shape: window_minutes 299/10079 (NOT 300/10080) and RELATIVE
 *   `resets_in_seconds` instead of absolute `resets_at`, with no credits block at all. Proves the
 *   duration classifier must tolerate vendor jitter and that both reset encodings are real.
 * CAPTURED VERBATIM FROM: ~/.codex/sessions/2025/09/30/rollout-2025-09-30T01-57-41-019997b2-321d-7443-acd8-188885a7610e.jsonl
 *   line 7
 */
const LEGACY_RELATIVE_RESETS_RAW =
  '{"primary":{"used_percent":0.0,"window_minutes":299,"resets_in_seconds":17940},"secondary":{"used_percent":0.0,"window_minutes":10079,"resets_in_seconds":604740}}';

/**
 * A window whose stated duration is 0 minutes, and a null credits block - a REAL payload our
 *   classifier cannot name. The drift case, captured rather than imagined.
 * CAPTURED VERBATIM FROM: ~/.codex/sessions/2026/06/03/rollout-2026-06-03T10-08-00-019e8c4f-7df6-7b13-8b09-0b0df9451387.jsonl
 *   line 17
 */
const UNRECOGNISED_WINDOW_RAW =
  '{"limit_id":"codex","limit_name":null,"primary":{"used_percent":0.0,"window_minutes":0,"resets_at":1780470487},"secondary":null,"credits":null,"plan_type":"plus","rate_limit_reached_type":null}';

/**
 * primary AND secondary null, mid-session, on a HEALTHY account: the 70 OTHER token_count
 *   lines in this same file all read 27% weekly. Absent windows mean 'not reported this turn', never
 *   'spent' - the old decoder called this shape FULL/exhausted.
 * CAPTURED VERBATIM FROM: ~/.codex/sessions/2026/07/22/rollout-2026-07-22T01-12-54-019f86bd-3211-71e2-8a94-e5d271f69810.jsonl
 *   line 50
 */
const NO_WINDOW_MIDSESSION_RAW =
  '{"limit_id":"codex","limit_name":null,"primary":null,"secondary":null,"credits":{"has_credits":false,"unlimited":false,"balance":"0"},"individual_limit":null,"plan_type":"prolite","rate_limit_reached_type":null}';

export const WEEKLY_ONLY_IDLE = JSON.parse(WEEKLY_ONLY_IDLE_RAW) as CodexRateLimits;
export const WEEKLY_ONLY_97 = JSON.parse(WEEKLY_ONLY_97_RAW) as CodexRateLimits;
export const WEEKLY_ONLY_SPENT = JSON.parse(WEEKLY_ONLY_SPENT_RAW) as CodexRateLimits;
export const BOTH_WINDOWS = JSON.parse(BOTH_WINDOWS_RAW) as CodexRateLimits;
export const LEGACY_RELATIVE_RESETS = JSON.parse(LEGACY_RELATIVE_RESETS_RAW) as CodexRateLimits;
export const UNRECOGNISED_WINDOW = JSON.parse(UNRECOGNISED_WINDOW_RAW) as CodexRateLimits;
export const NO_WINDOW_MIDSESSION = JSON.parse(NO_WINDOW_MIDSESSION_RAW) as CodexRateLimits;
