//! Pager views. `frontend-runtime` exposes reusable terminal presentation;
//! service-specific Grok panes remain behind `grok-runtime`.

#[cfg(feature = "frontend-runtime")]
pub mod completion_dropdown;
#[cfg(feature = "frontend-runtime")]
pub mod file_search;
#[cfg(feature = "frontend-runtime")]
pub mod history_search;
#[cfg(feature = "frontend-runtime")]
pub mod modal_window;
#[cfg(feature = "frontend-runtime")]
pub mod permission_presentation;
#[cfg(feature = "frontend-runtime")]
pub mod prompt_suggestion;
#[cfg(feature = "frontend-runtime")]
pub mod prompt_widget;
#[cfg(feature = "grok-runtime")]
pub mod question_view;
#[cfg(feature = "frontend-runtime")]
pub mod slash_dropdown;
#[cfg(feature = "frontend-runtime")]
pub mod status_bar;
#[cfg(feature = "frontend-runtime")]
pub mod suggestion_controller;
#[cfg(feature = "frontend-runtime")]
pub mod timeline;

#[cfg(feature = "grok-runtime")]
pub mod agent;
#[cfg(feature = "grok-runtime")]
pub mod agent_status;
#[cfg(feature = "grok-runtime")]
pub mod agents_modal;
#[cfg(feature = "grok-runtime")]
pub mod announcements;
#[cfg(feature = "grok-runtime")]
pub mod block_viewer;
#[cfg(feature = "grok-runtime")]
pub mod btw_overlay;
#[cfg(feature = "grok-runtime")]
pub mod context_bar;
#[cfg(feature = "grok-runtime")]
pub mod credit_bar;
#[cfg(feature = "grok-runtime")]
pub mod dashboard;
#[cfg(feature = "grok-runtime")]
pub mod debug_style;
#[cfg(feature = "grok-runtime")]
pub mod extensions_modal;
#[cfg(feature = "grok-runtime")]
pub mod fps_hud;
#[cfg(feature = "grok-runtime")]
pub mod goal_detail;
#[cfg(feature = "grok-runtime")]
pub mod import_claude_modal;
#[cfg(feature = "grok-runtime")]
pub mod jump;
#[cfg(feature = "grok-runtime")]
pub mod list_pane;
#[cfg(feature = "grok-runtime")]
pub mod mcps_modal;
#[cfg(feature = "grok-runtime")]
pub mod memory_modal;
#[cfg(feature = "grok-runtime")]
pub mod modal;
#[cfg(feature = "grok-runtime")]
pub mod new_worktree_dialog;
#[cfg(feature = "grok-runtime")]
pub mod overlay;
#[cfg(feature = "grok-runtime")]
pub mod overlay_list;
#[cfg(feature = "grok-runtime")]
pub mod permission_view;
#[cfg(feature = "grok-runtime")]
pub mod persona_detail;
#[cfg(feature = "grok-runtime")]
pub mod picker;
#[cfg(feature = "grok-runtime")]
pub mod plan_approval_view;
#[cfg(feature = "grok-runtime")]
pub mod privacy_banner;
#[cfg(feature = "grok-runtime")]
pub mod progress_bar;
#[cfg(feature = "grok-runtime")]
pub mod queue_pane;
#[cfg(feature = "grok-runtime")]
pub mod rewind;
#[cfg(feature = "grok-runtime")]
pub mod scroll_debug_hud;
#[cfg(feature = "grok-runtime")]
pub mod session_picker;
#[cfg(feature = "grok-runtime")]
pub mod session_title;
#[cfg(feature = "grok-runtime")]
pub mod settings_modal;
#[cfg(feature = "grok-runtime")]
pub mod shortcuts_bar;
#[cfg(feature = "grok-runtime")]
pub mod shortcuts_help;
#[cfg(feature = "grok-runtime")]
pub mod subagent_catalog_pane;
#[cfg(feature = "grok-runtime")]
pub mod tasks_pane;
#[cfg(feature = "grok-runtime")]
pub mod todo_pane;
#[cfg(feature = "grok-runtime")]
pub mod turn_status;
#[cfg(feature = "grok-runtime")]
pub mod tutorial;
#[cfg(feature = "grok-runtime")]
pub mod usage_modal;
#[cfg(feature = "grok-runtime")]
pub mod welcome;
#[cfg(feature = "grok-runtime")]
pub mod workflows;
