use serde::Deserialize;
use serde_json::{Value, json};
use zer0_room_protocol::{JsonRpcRequest, RoomEvent, decode_server_frame};

#[derive(Deserialize)]
struct Manifest {
    cases: Vec<CorpusCase>,
}

#[derive(Deserialize)]
struct CorpusCase {
    file: String,
    id: String,
    kind: String,
    expect: CorpusExpectation,
}

#[derive(Deserialize)]
struct CorpusExpectation {
    valid: bool,
}

const MANIFEST: &str = include_str!("../../../../protocol/conformance/v1/manifest.json");

fn corpus_bytes(file: &str) -> &'static [u8] {
    match file {
        "frame-exact-limit.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/frame-exact-limit.bin")
        }
        "frame-over-limit.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/frame-over-limit.bin")
        }
        "invalid-utf8.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/invalid-utf8.bin")
        }
        "string-id.bin" => include_bytes!("../../../../protocol/conformance/v1/string-id.bin"),
        "max-safe-id.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/max-safe-id.bin")
        }
        "unsafe-id.bin" => include_bytes!("../../../../protocol/conformance/v1/unsafe-id.bin"),
        "fractional-id.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/fractional-id.bin")
        }
        "request-extra.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/request-extra.bin")
        }
        "notification-extra.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/notification-extra.bin")
        }
        "success-null.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/success-null.bin")
        }
        "missing-result.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/missing-result.bin")
        }
        "both-result-error.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/both-result-error.bin")
        }
        "chunk-ascii-max.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/chunk-ascii-max.bin")
        }
        "chunk-ascii-over.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/chunk-ascii-over.bin")
        }
        "chunk-emoji-max.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/chunk-emoji-max.bin")
        }
        "chunk-emoji-over.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/chunk-emoji-over.bin")
        }
        "chunk-index-max.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/chunk-index-max.bin")
        }
        "chunk-index-over.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/chunk-index-over.bin")
        }
        "activity-known.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/activity-known.bin")
        }
        "activity-unknown.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/activity-unknown.bin")
        }
        "agent-status-valid.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/agent-status-valid.bin")
        }
        "agent-status-empty.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/agent-status-empty.bin")
        }
        "agent-status-percent-over.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/agent-status-percent-over.bin")
        }
        "agent-status-fractional.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/agent-status-fractional.bin")
        }
        "agent-status-unsafe-reset.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/agent-status-unsafe-reset.bin")
        }
        "agent-status-unknown.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/agent-status-unknown.bin")
        }
        "event-invalid-calendar-date.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/event-invalid-calendar-date.bin")
        }
        "backend-empty.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/backend-empty.bin")
        }
        "backend-message.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/backend-message.bin")
        }
        "backend-error.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/backend-error.bin")
        }
        "backend-unknown.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/backend-unknown.bin")
        }
        "backend-empty-field.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/backend-empty-field.bin")
        }
        // Lane MN found these four already generated by generate.mjs but never committed: the
        // corpus had drifted from its own generator, so `agent.mode` and `hop.*` had wire cases
        // nothing was testing. Regenerating to add the notice fixtures brought them along; they
        // are wired here rather than dropped, because a fixture the generator emits and this match
        // does not name is a panic waiting for the next person to regenerate.
        "agent-mode-valid.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/agent-mode-valid.bin")
        }
        "agent-mode-unknown.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/agent-mode-unknown.bin")
        }
        "hop-max-valid.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/hop-max-valid.bin")
        }
        "hop-both-budget-names.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/hop-both-budget-names.bin")
        }
        "notice-valid.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/notice-valid.bin")
        }
        // Expected VALID: an unrecognized cause from a newer host must reduce and render generically
        // rather than be rejected. Both halves agree because neither closes the cause on the wire.
        "notice-unknown-cause.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/notice-unknown-cause.bin")
        }
        "notice-missing-detail.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/notice-missing-detail.bin")
        }
        "notice-detail-over.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/notice-detail-over.bin")
        }
        "notice-detail-max.bin" => {
            include_bytes!("../../../../protocol/conformance/v1/notice-detail-max.bin")
        }
        unexpected => panic!("non-trace corpus file is not a literal-byte consumer: {unexpected}"),
    }
}

fn frame_content(raw: &[u8]) -> &[u8] {
    assert_eq!(raw.last(), Some(&b'\n'), "corpus fixture must be LF framed");
    &raw[..raw.len() - 1]
}

fn validates(case: &CorpusCase) -> bool {
    let raw = corpus_bytes(&case.file);
    match case.kind.as_str() {
        "request" => serde_json::from_slice::<JsonRpcRequest>(frame_content(raw)).is_ok(),
        "notification" | "response" => decode_server_frame(frame_content(raw)).is_ok(),
        "event" => serde_json::from_slice::<Value>(frame_content(raw))
            .ok()
            .and_then(|value| RoomEvent::from_value(value).ok())
            .is_some(),
        other => panic!("non-trace corpus kind has no protocol validator: {other}"),
    }
}

#[test]
fn shared_non_frame_corpus_uses_production_protocol_validators() {
    let manifest: Manifest = serde_json::from_str(MANIFEST).expect("shared corpus manifest");
    let cases = manifest
        .cases
        .iter()
        .filter(|case| case.kind != "trace" && case.kind != "frame")
        .collect::<Vec<_>>();
    assert!(
        !cases.is_empty(),
        "manifest must contain non-frame protocol cases"
    );
    for case in cases {
        assert_eq!(validates(case), case.expect.valid, "{}", case.id);
    }
}

#[test]
fn permission_wire_preserves_opaque_ids_and_bounds_the_digit_surface() {
    let event = |payload: Value| {
        json!({
            "protocol": "zer0.room",
            "version": 1,
            "sessionId": "chat-test",
            "eventSeq": "1",
            "eventId": "event-permission",
            "turnId": "turn-1",
            "occurredAt": "2026-01-01T00:00:00Z",
            "type": "permission.requested",
            "payload": payload
        })
    };

    assert!(
        RoomEvent::from_value(event(json!({
            "agent": "claude",
            "askId": "  opaque\t\u{001b}[31m",
            "options": [{"optionId": "  allow\t", "name": "Allow"}]
        })))
        .is_ok()
    );

    assert!(
        RoomEvent::from_value(event(json!({
            "agent": "claude",
            "askId": "x".repeat(4097)
        })))
        .is_err()
    );

    let options = (0..10)
        .map(|index| json!({"optionId": format!("option-{index}")}))
        .collect::<Vec<_>>();
    assert!(
        RoomEvent::from_value(event(json!({
            "agent": "claude",
            "askId": "ask-1",
            "options": options
        })))
        .is_err()
    );
}

#[test]
fn agent_mode_word_must_be_a_known_string_when_present() {
    let event = |word: Value| {
        json!({
            "protocol": "zer0.room",
            "version": 1,
            "sessionId": "chat-test",
            "eventSeq": "1",
            "eventId": "event-mode",
            "turnId": "turn-1",
            "occurredAt": "2026-01-01T00:00:00Z",
            "type": "agent.mode",
            "payload": {
                "agent": "claude",
                "modeId": "default",
                "status": "active",
                "word": word
            }
        })
    };

    assert!(RoomEvent::from_value(event(json!("auto"))).is_ok());
    for invalid in [
        json!(null),
        json!(1),
        json!({"label": "auto"}),
        json!("automatic"),
    ] {
        assert!(RoomEvent::from_value(event(invalid)).is_err());
    }
}
